baseURL = "https://stubborncode.com/"
languageCode = "en-us"
title = "Stubborn Code"
theme = "hyde-x"

[author]
name = "Teo"

[params]
home = "Posts"
portfolio = "Portfolio"
highlight = "railscasts"
github = "https://github.com/deepintocode"
twitter = "https://twitter.com/deepintocode"
linkedin = "https://www.linkedin.com/in/teomanos/"
googleAnalytics = "UA-119889973-1"
staticmanURL = "https://api.staticman.net/v2/entry/deepintocode/stubborn-code/master/comments"

[blackfriday] 
hrefTargetBlank = true