baseURL = "https://stubborncode.com/"
languageCode = "en-us"
title = "Stubborn Code"
theme = "hyde-x"

[author]
name = "Teo"

[params]
home = "Posts"
highlight = "railscasts"
github = "https://github.com/todorare"
twitter = "https://twitter.com/todorare"
googleAnalytics = "UA-119889973-1"
staticmanURL = "https://api.staticman.net/v2/entry/todorare/stubborn-code/master/comments"